name: SweetData
version: '${version}'
main: top.mrxiaom.sweetdata.SweetData
api-version: 1.13
softdepend: [ PlaceholderAPI ]
authors: [ MrXiaoM ]
folia-supported: true
# PluginBase Libraries ${libraries_config}
commands:
  sweetdata:
    description: 'The main command of SweetData'
    aliases: [ sdata, data ]
